// USA tech / startup LARP lexicon — YC & accelerator culture, VC/fundraising
// theater, founder/build-in-public Twitter, LinkedIn thought-leader cringe,
// AI-wrapper grift, indie-hacker passive-income, and new-grad/intern flexing.
// Refreshed for 2025-2026 startup culture.
//
// Terms can be written naturally (apostrophes, punctuation) — the scorer in
// larp.ts normalizes both the transcript and these terms the same way before
// matching, so "we're not a wrapper" matches spoken "we are not a wrapper" too.
//
// Weights: 1 = mild / context-dependent, 4 = egregious pure performance.
// Single ultra-common words are deliberately excluded to avoid false positives.

export const STARTUP_BUZZWORDS: Record<string, number> = {
  // ---- YC / accelerator theater ----
  "y combinator": 2,
  yc: 1,
  "yc-backed": 3,
  "we're yc-backed": 3,
  "we got into yc": 2,
  "yc adjacent": 4,
  "ex-yc": 3,
  "in the current batch": 2,
  "my batchmates": 2,
  batchmate: 2,
  "demo day": 1,
  "group office hours": 1,
  "garry told us": 3,
  "garry tan personally": 4,
  "thiel fellow": 2,
  "thiel fellowship": 2,
  "founder mode": 3,
  "high agency": 3,
  "ambitious misfits": 3,
  "do things that don't scale": 2,
  "talk to users": 1,
  "design partners": 2,
  "letters of intent": 2,
  "our tam is massive": 3,
  "1m arr by demo day": 3,
  "applying to yc": 1,

  // ---- fundraising / VC theater ----
  oversubscribed: 3,
  "soft-circled": 3,
  "soft circled": 3,
  "warm intro": 2,
  "tier 1 vc": 3,
  "tier-1 vc": 3,
  "tier one vcs": 3,
  "we had to turn money away": 4,
  "we're not really raising but": 4,
  "not really raising": 3,
  "closed our round": 2,
  "the round closed itself": 4,
  "raising on a safe": 1,
  "uncapped safe": 2,
  "strategic angels": 3,
  "operator angels": 2,
  "big names on the cap table": 4,
  "can't say who but you'd know them": 4,
  "can't say who": 3,
  "in talks with sequoia": 4,
  "in talks with a16z": 4,
  "sequoia reached out": 4,
  "term sheet": 2,
  "we have term sheets": 3,
  "competitive term sheet": 2,
  "preempted our round": 3,
  "they preempted us": 3,
  "we got fomo'd": 3,
  "creating fomo": 2,
  "hot round": 2,
  "party round": 1,
  "post-money valuation": 1,
  "pre-revenue": 2,
  "default alive": 2,
  "default dead": 2,
  "ramen profitable": 2,
  "past ramen profitable": 3,
  "infinite runway": 3,
  "runway for days": 3,
  runway: 1,
  "inbound only": 3,
  "the round was inbound": 3,
  "we turned down the lead": 4,
  "down round": 1,
  "bridge round": 1,
  "extension round": 2,
  "we own the cap table": 3,
  "vibe round": 3,
  "cap table": 1,
  "seed round": 1,
  "pre-seed": 1,
  "series a": 1,

  // ---- founder / build-in-public Twitter ----
  "build in public": 2,
  "building in public": 2,
  buildinpublic: 2,
  "just shipped": 2,
  "shipping daily": 3,
  "we ship fast": 3,
  "i ship fast": 3,
  shipping: 1,
  grindset: 4,
  "rise and grind": 4,
  "locked in": 2,
  "the great lock in": 4,
  "4am no days off": 4,
  "no days off": 2,
  "996": 2,
  "we're so back": 2,
  "the team is so back": 3,
  "we're so early": 4,
  "we are so early": 4,
  lfg: 3,
  "dms open": 2,
  wagmi: 3,
  ngmi: 3,
  "this is the way": 3,
  "obsessed with the problem": 3,
  "changing the world": 3,
  "the future of": 2,
  "we're just getting started": 3,
  "asymmetric bet": 3,
  "deep work": 1,
  maxxing: 3,
  "in the trenches": 3,

  // ---- talent / hiring flex ----
  cracked: 2,
  "i'm cracked": 3,
  "cracked engineer": 3,
  "hiring cracked engineers": 3,
  "10x engineer": 4,
  "rockstar developer": 3,
  "ninja coder": 3,
  "spiky talent": 4,
  "high signal": 3,
  "built different": 3,
  "i'm built different": 3,
  "founding engineer": 3,
  "0 to 1": 2,
  "zero to one": 2,

  // ---- LinkedIn thought-leader cringe ----
  "humbled to announce": 4,
  "deeply humbled": 4,
  "blessed and humbled": 4,
  "humbled to share": 4,
  "thrilled to announce": 3,
  "excited to announce": 2,
  "thrilled to share": 2,
  "beyond excited to share": 3,
  "let that sink in": 4,
  "unpopular opinion": 3,
  "hot take": 3,
  "i made a hard decision today": 4,
  "rejection taught me": 3,
  "lessons from my failure": 3,
  "my mentor told me": 3,
  "a janitor at the airport told me": 4,
  "fractional cmo": 2,
  "fractional cfo": 2,
  "fractional everything": 3,
  "thought leader": 3,
  "thought partner": 3,
  "mentor to millions": 4,
  "helping founders scale": 3,
  "i help founders": 2,
  "serial entrepreneur": 2,
  "category creator": 3,
  "category-defining": 4,
  "comment yes if you agree": 4,
  "save this post": 2,
  "while you were sleeping": 4,
  "from zero to hero": 3,
  "delusional optimism": 3,
  "generational company": 4,
  "generational opportunity": 3,
  "move the needle": 2,

  // ---- AI hype / wrapper grift ----
  "ai-native": 3,
  "ai native": 3,
  "ai-first": 3,
  agentic: 3,
  "agentic ai": 3,
  "agentic layer": 4,
  "we're the agentic layer for": 4,
  "ai agents": 2,
  "ai employees": 4,
  "digital workers": 3,
  "autonomous agents": 3,
  "agent swarm": 4,
  "multi-agent orchestration": 3,
  "we replaced our team with agents": 4,
  "we replaced our sdrs with agents": 4,
  "ai sdr": 2,
  "our moat": 3,
  "the moat is the data": 3,
  "proprietary model": 3,
  "proprietary llm": 4,
  "we fine-tuned our own model": 3,
  "we built our own foundation model": 4,
  "foundation model": 2,
  "we're an ai lab": 4,
  "we're basically openai for": 4,
  "the openai for": 4,
  "the chatgpt for": 4,
  "the cursor for": 3,
  "it's not just a wrapper": 4,
  "we're not a wrapper": 4,
  "not just a gpt wrapper": 4,
  "it's just a wrapper": 2,
  "wrappers all the way down": 2,
  "rag pipeline": 2,
  "agentic rag": 3,
  "mcp-native": 3,
  "prompt engineer": 2,
  "context engineering": 2,
  "vibe coding": 2,
  "vibe coded": 3,
  "i don't even code anymore": 3,
  agi: 3,
  "pre-agi": 4,
  "self-improving": 3,
  "1000x productivity": 4,
  "one-person billion dollar company": 4,
  "intelligence too cheap to meter": 4,
  "copilot for": 2,
  "the model is the product": 3,

  // ---- indie hacker / passive income ----
  "passive income": 3,
  "make money while i sleep": 4,
  "i quit my 9-5": 3,
  "escape the 9-5": 3,
  "fire the boss": 3,
  "1000 true fans": 2,
  "build once sell twice": 3,
  "audience first": 2,
  "micro-saas": 1,
  "shipped 12 products this year": 3,
  "shipping is a feeling": 3,
  "launch in days not weeks": 2,
  "vibe coded it in a weekend": 3,
  "zero to one in a weekend": 3,
  "digital nomad": 2,
  "location independent": 2,
  "working from bali": 3,
  "laptop lifestyle": 4,
  "time freedom": 3,
  "financial freedom": 3,
  "fuck you money": 2,
  solopreneur: 1,
  "productize yourself": 3,
  "digital product empire": 4,
  "info product": 2,
  "cohort-based course": 2,
  "i'll drop the playbook": 3,
  "here's the playbook": 3,
  "distribution is everything": 2,
  "compounding in public": 3,
  "the algorithm rewards consistency": 3,
  "stripe screenshot": 2,
  "bootstrapped": 1,

  // ---- new-grad / intern flex ----
  "incoming swe": 2,
  "incoming swe @": 3,
  "return offer": 1,
  "open to work": 1,
  faang: 1,
  manga: 2,
  "big tech": 1,
  "t1 company": 3,
  "ex-faang": 3,
  "grinding leetcode": 2,
  "on the grind": 2,
  "the grind": 2,
  "so cooked": 2,
  "coffee chat": 1,
  "pick your brain": 2,
  "referral loop": 2,
  "neetcode 150": 1,
  "grind 500 problems": 2,
  "serial hackathon winner": 3,
  rizz: 2,
  "touched grass": 1,
  "it's so over": 2,

  // ---- generic startup poison (still valid) ----
  synergy: 3,
  synergies: 3,
  leverage: 2,
  leveraging: 2,
  paradigm: 3,
  ecosystem: 2,
  disrupt: 3,
  disruptive: 3,
  disrupting: 3,
  "we're disrupting": 4,
  web3: 3,
  blockchain: 2,
  "first principles": 2,
  flywheel: 2,
  "data flywheel": 2,
  moat: 1,
  "north star": 1,
  "north star metric": 1,
  "secret sauce": 2,
  "low-hanging fruit": 2,
  "circle back": 2,
  "boil the ocean": 2,
  holistic: 2,
  frictionless: 2,
  "next-gen": 2,
  "cutting-edge": 2,
  "best-in-class": 2,
  "game-changer": 3,
  "game changer": 3,
  "game-changing": 3,
  "deep dive": 1,
  "double-click": 2,
  "table stakes": 2,
  ideate: 2,
  operationalize: 2,
  revolutionary: 2,
  transformative: 2,
  hypergrowth: 2,
  unicorn: 1,
  "growth hacking": 3,
  "value-add": 2,
  "value add": 2,
  "deep tech": 2,
  "hard tech": 2,
  "stealth mode": 3,
  "stealth startup": 3,
  "building in stealth": 3,
  "product-market fit": 1,
  pmf: 1,
  "we found pmf": 2,
  traction: 1,
  mrr: 1,
  arr: 1,
};

export const STARTUP_VAGUE = [
  // generic hype filler
  "we're seeing crazy traction",
  "the numbers speak for themselves",
  "we're growing really fast",
  "users are loving it",
  "the response has been insane",
  "we're heads down building",
  "a lot of inbound interest",
  "some really exciting conversations",
  "the metrics are looking great",
  "we're crushing our targets",
  "early signal is super strong",
  "we're basically printing money",
  "the market is huge",
  "the market is massive",
  "it's a no-brainer",
  "we're onto something",
  "this is a generational opportunity",
  "we're just getting started",
  "we're moving incredibly fast",
  "big things coming",
  "can't share details yet",
  "numbers are up only",
  "more soon",
  "watch this space",
  "we're cooking",
  "trust the process",
  "the energy is unreal",
  "the vision is clear",
  // fundraising vague
  "some great names are involved",
  "a few funds you'd recognize",
  "we have plenty of runway",
  "investors keep reaching out",
  "we'll have news soon",
  "not optimizing for valuation",
  "we're well capitalized",
  "the deal was massively competitive",
  // indie / nomad vague
  "multiple six figures",
  "high six figures",
  "more than my old salary",
  "it basically runs itself",
  "mostly hands-off at this point",
  "a portfolio of products",
  // intern / job vague
  "the market is so cooked",
  "just trying to stay locked in",
  "i'm kind of built different",
  "a lot of cool things in the pipeline",
  "i'm just heads down building",
  "putting in the reps",
  "doing the work",
  // generic
  "a lot",
  "tons",
  "huge",
  "massive",
  "literally",
  "basically",
  "honestly",
  "the future",
  "next level",
  "life-changing",
  "this changes everything",
  "manifesting",
  "lowkey",
  "highkey",
];

export const STARTUP_AUTHORITY = [
  // YC / VC name-drop authority
  "when i was at yc",
  "my yc partner told me",
  "as a yc founder",
  "the partners loved our application",
  "i've raised from tier 1 vcs",
  "i'm a thiel fellow",
  "paul graham said",
  "my buddy who's a partner at sequoia",
  "the a16z guys told me",
  "i know how these funds think",
  "the smart money is already in",
  "i can get you a warm intro to anyone",
  // founder / operator authority
  "as a 3x founder",
  "after my last exit",
  "having scaled multiple companies to exit",
  "i've mentored hundreds of founders",
  "i talk to founders every day",
  "every great founder i know",
  "the best founders all",
  "as a thought leader",
  "i've been in the trenches",
  "i've shipped to millions of users",
  "trust me i've seen this before",
  "i've done this before",
  // AI authority
  "i talked to someone at openai",
  "my friend on the anthropic team told me",
  "i was in the room when",
  "i've been doing ai since before chatgpt",
  "we got early access to the new model",
  "i can't say who but a big lab",
  // indie authority
  "marc lou does exactly this",
  "pieter levels built nomadlist this way",
  "i was build-in-public before it was cool",
  "ask anyone in the indie hacker community",
  "naval basically says the same thing",
  // intern authority
  "i did a coffee chat with a staff engineer",
  "my mentor at meta told me",
  "ex-faang here so i know how interviews work",
  "the founder personally reached out to me",
  "i was basically a founding engineer",
  "i've got connections at all the t1 companies",
  // generic
  "trust me",
  "believe me",
  "everyone knows",
  "no doubt",
  "mark my words",
  "i guarantee",
  "people don't talk about this",
  "most people don't understand",
  "here's what nobody tells you",
];
