// USA tech / internship / YC / startup LARP lexicon — mined from the classic
// LinkedIn-post and founder-twitter patterns we parody in larpPosts.ts.

export const STARTUP_BUZZWORDS: Record<string, number> = {
  // YC / fundraising theater
  "y combinator": 3,
  yc: 2,
  "stealth mode": 3,
  "stealth startup": 3,
  "seed round": 2,
  "pre-seed": 2,
  "series a": 1,
  "quietly closed": 3,
  "can't share": 3,
  "cant share": 3,
  "number i can't share": 4,
  "term sheet": 2,
  "cap table": 2,
  runway: 2,
  "product-market fit": 2,
  pmf: 2,
  traction: 2,
  "building in public": 3,
  "ship fast": 2,
  "move fast": 2,
  "default alive": 2,
  "default dead": 2,

  // Intern / new-grad performance
  intern: 1,
  internship: 1,
  "return offer": 2,
  "full-time offer": 2,
  faang: 2,
  "big tech": 2,
  leetcode: 2,
  "referral loop": 2,
  "coffee chat": 2,
  networking: 1,
  "cracked engineer": 3,
  "10x engineer": 3,
  "rockstar developer": 3,
  "ninja coder": 3,

  // LinkedIn-core LARP
  "thought leader": 3,
  "girl dad": 2,
  "boy dad": 2,
  "humbled to announce": 3,
  "excited to announce": 2,
  "thrilled to share": 2,
  "integrity over income": 3,
  "we are not the same": 3,
  "never underestimate": 2,
  "changed how i think": 3,
  "what happened next": 3,
  "agree?": 2,
  "here's the playbook": 3,
  "here is the playbook": 3,
  "thread on": 2,
  "a thread": 2,
  "course launching soon": 3,
  "mentor to millions": 3,
  "serial entrepreneur": 2,
  "fractional cmo": 2,
  "keynote speaker": 2,

  // Twitter / indie hacker LARP
  "no code": 2,
  "no team": 2,
  "no product": 3,
  "just vibes": 4,
  mrr: 2,
  arr: 2,
  "$0 to": 3,
  "prints money": 3,
  notion: 1,
  "passive income": 2,
  "while i was asleep": 3,
  "on a beach in bali": 3,
  "ai agents": 2,
  "replaced my whole team": 4,
  "revenue is theoretical": 4,
  "morale is infinite": 3,
  "building in public soon": 3,
  "maybe": 1,
  "can't say who": 3,
  "will change everything": 3,

  // Generic startup poison (also in base lexicon, weighted for this domain)
  synergy: 3,
  synergies: 3,
  leverage: 2,
  leveraging: 2,
  paradigm: 3,
  ecosystem: 2,
  disrupt: 3,
  disruptive: 3,
  disrupting: 3,
  web3: 3,
  blockchain: 2,
  crypto: 1,
  "ai-native": 3,
  "ai native": 3,
  agentic: 2,
  "llm-powered": 2,
  "10x": 2,
  "100x": 2,
  scalable: 1,
  "north star": 2,
  "value-add": 2,
  "value add": 2,
  "low-hanging fruit": 2,
  bandwidth: 1,
  "circle back": 2,
  "move the needle": 2,
  holistic: 2,
  frictionless: 2,
  "next-gen": 2,
  "next gen": 2,
  "cutting-edge": 2,
  "cutting edge": 2,
  "best-in-class": 2,
  "best in class": 2,
  "game-changer": 3,
  "game changer": 3,
  "game-changing": 3,
  "deep dive": 1,
  "boil the ocean": 2,
  "first principles": 2,
  moat: 1,
  flywheel: 2,
  hypergrowth: 2,
  unicorn: 1,
  pivot: 1,
  "growth hacking": 3,
  "secret sauce": 2,
  "double-click": 2,
  "double click": 2,
  "table stakes": 2,
  unpack: 1,
  ideate: 2,
  operationalize: 2,
  revolutionary: 2,
  transformative: 2,
  seamless: 1,
  robust: 1,
  synergistic: 3,
};

export const STARTUP_VAGUE = [
  "a lot",
  "tons",
  "huge",
  "massive",
  "everyone knows",
  "obviously",
  "literally",
  "basically",
  "honestly",
  "to be honest",
  "kind of",
  "sort of",
  "stuff",
  "things",
  "whatever",
  "you know",
  "i mean",
  "the future",
  "next level",
  "super important",
  "really big",
  "insane traction",
  "crazy growth",
  "life-changing",
  "game changing",
  "mind blown",
  "this changes everything",
  "big things coming",
  "stay tuned",
  "more soon",
  "trust the process",
  "manifesting",
  "vibes only",
  "it's giving",
  "lowkey",
  "highkey",
];

export const STARTUP_AUTHORITY = [
  "trust me",
  "believe me",
  "obviously",
  "everyone knows",
  "no doubt",
  "for sure",
  "100%",
  "full stop",
  "period",
  "mark my words",
  "i guarantee",
  "i interviewed",
  "millionaires told me",
  "founders told me",
  "insiders say",
  "people don't talk about this",
  "most people don't understand",
  "here's what nobody tells you",
  "hot take",
  "unpopular opinion",
  "controversial but",
];
